### PR TITLE
2015-12-03

### PR DESCRIPTION
**Pull request by mfulton26**
- a [`set`](https://docs.python.org/3.8/library/stdtypes.html#set-types-set-frozenset) can be used to maintain a collection of unique items; a `list`
  is great for ordered, non-unique stuff but maintaining a unique
  collection with a `list` requires scanning (linearly) the list to
  check/add/remove an item while a `set` does these operations in
  constant time because it "hashes" the value
- `def` can be used to define a reusable block of code (a function)
- a `dict` (dictionary) can be used to maintain a mapping of keys to
  values, e.g. direction "chars" to lambdas; these values can then be
  looked up in constant time (as opposed to an if/elif chain which is
  is a linear lookup) and then be used (e.g. invoking a lambda/function)
- a [`slice`](https://docs.python.org/3.8/glossary.html#term-slice) can be used to select a sequence or range from a collection
  e.g. list[3:9:2] will return the values at indexes 3, 5, & 7
  syntax: `list[start:end:step]` where end is exclusive
- a `set` can also be unioned/merged with another set:
  - `a.union(b)`
  - `a | b`
- a list/tuple can be "spread" to fill parameters using values in the
  list/tuple (e.g. `def sum(a, b)` can be called with `sum(1, 2)` or
  `sum(*[1,2])`)

### CODE REVIEW

**Comment by FormulaTranslator** [comment]
Awesome! I had never heard of sets before. Also, I didn't think to host equations in a dictionary before. 1 question though, your solution is off by 1 on the second part (it prints 2361 and the answer should be 2360). I tried to troubleshoot it, but I don't know enough about sets. Would you know why?

**Comment by mfulton26** [comment]
hmmm…

it prints

```out
2592
2360
```

for me…

**Comment by mfulton26** [comment]
oh, what version of Python are you using? Python 2 or 3

**Comment by FormulaTranslator** [comment]
v3

**Comment by FormulaTranslator** [comment]
I figured it out! It's your line 2 (  houses = set([house])  ). My IDE was complaining about the [] around house, saying it was redundant and not needed, so I took them out. Turns out, my IDE is dumb. What do the [] do?

**Comment by mfulton26** [comment]
oh, `set((0, 0))` probably creates a `set([0])` (i.e. a collection of unique values containing the int `0`) while `set([(0, 0])` creates a `set([(0, 0])` (i.e. a collection of  unique values containing the tuple `(0, 0)`)

**Comment by mfulton26** [comment]
i.e. the tuple in `set((0, 0))` was being processed like `set([0, 0])` which  results in `set([0])`

**Comment by FormulaTranslator** [comment]
Update, the exact error I was getting was "function call can be replaced with set literal", so i looked it up and it wanted me to put {house} instead of set([house])

**Comment by mfulton26** [comment]
oooh, fancy, I do not code in Python regularly so there are things for me
to learn too; thank you :D

**Comment by FormulaTranslator** [comment]
Thank you so much for this! I am very impressed with the amount of time and effort you are putting into reviewing my code. 
Also, just so you know, I am changing my code to match your much more elegant code. However, I'm not merging it through GitHub. I am typing it out myself so as to learn it better.

**Comment by mfulton26** [comment]
makes sense to me!

FYI: I'll just see if I can just do one of these a workday or something, I probably won't get through them too quickly but I'll keep going, I'll pull from your repo before taking a look at a solution in case you go make changes whenever

I enjoy code so I think this is mutually fun/enlightening (plus gives me an excuse to improve my rusty Python skills)

**Pull request closed without merging**
